-- MySQL Script generated by MySQL Workbench
-- Wed Jan  7 22:02:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema health_project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema health_project_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `health_project_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `health_project_db` ;

-- -----------------------------------------------------
-- Table `health_project_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `registration_date` DATE NOT NULL,
  `gender` ENUM("M", "F") NULL,
  `age` INT NULL,
  `weight_kg` DECIMAL(4,1) NULL,
  `height_cm` DECIMAL(4,1) NULL,
  `resting_hr` DECIMAL NULL,
  `max_hr` DECIMAL NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`conditions` (
  `condition_id` INT NOT NULL AUTO_INCREMENT,
  `condition_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`condition_id`),
  UNIQUE INDEX `conditions_id_UNIQUE` (`condition_id` ASC) VISIBLE,
  UNIQUE INDEX `condition_UNIQUE` (`condition_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`users_conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`users_conditions` (
  `user_id` INT NOT NULL,
  `condition_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `condition_id`),
  INDEX `fk_users_conditions_conditions1_idx` (`condition_id` ASC) VISIBLE,
  CONSTRAINT `link_user_conditions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_project_db`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_users_conditions_conditions1`
    FOREIGN KEY (`condition_id`)
    REFERENCES `health_project_db`.`conditions` (`condition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`medications` (
  `medication_id` INT NOT NULL AUTO_INCREMENT,
  `medication_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`medication_id`),
  UNIQUE INDEX `idmedications_UNIQUE` (`medication_id` ASC) VISIBLE,
  UNIQUE INDEX `medicationscol_UNIQUE` (`medication_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`users_medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`users_medications` (
  `user_id` INT NOT NULL,
  `medication_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `medication_id`),
  INDEX `fk_users_medications_medications1_idx` (`medication_id` ASC) VISIBLE,
  CONSTRAINT `link_user_medications_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_project_db`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_users_medications_medications1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `health_project_db`.`medications` (`medication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`activity_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`activity_types` (
  `activity_type_id` INT NOT NULL AUTO_INCREMENT,
  `activity_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`activity_type_id`),
  UNIQUE INDEX `idactivity_type_UNIQUE` (`activity_type_id` ASC) VISIBLE,
  UNIQUE INDEX `activity_type_name_UNIQUE` (`activity_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`sleep_stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`sleep_stages` (
  `stage_id` INT NOT NULL AUTO_INCREMENT,
  `sleep_stage` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`stage_id`),
  UNIQUE INDEX `idsleep_UNIQUE` (`stage_id` ASC) VISIBLE,
  UNIQUE INDEX `sleep_stage_UNIQUE` (`sleep_stage` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`readings` (
  `user_id` INT NOT NULL DEFAULT 000.0,
  `timestamp` TIMESTAMP NOT NULL,
  `activity_type_id` INT NOT NULL,
  `sleep_stage_id` INT NULL,
  `heart_rate` DECIMAL(4,1) NULL,
  `activity_intensity` DECIMAL(3,2) NULL,
  `steps_5min` INT NULL,
  `calories_5min` DECIMAL(3,2) NULL,
  `hrv_rmssd` DECIMAL(3,1) NULL,
  `stress_score` INT NULL,
  `confidence_score` DECIMAL(4,3) NULL,
  `signal_quality` DECIMAL(4,3) NULL,
  `skin_temperature` DECIMAL(3,1) NULL,
  `device_battery` INT NULL,
  `elevation_gain` INT NULL,
  PRIMARY KEY (`user_id`, `timestamp`),
  INDEX `fk_readings_activity_type1_idx` (`activity_type_id` ASC) VISIBLE,
  INDEX `fk_readings_sleep_stages1_idx` (`sleep_stage_id` ASC) VISIBLE,
  CONSTRAINT `readings_heart_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_project_db`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_readings_activity_type1`
    FOREIGN KEY (`activity_type_id`)
    REFERENCES `health_project_db`.`activity_types` (`activity_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_readings_sleep_stages1`
    FOREIGN KEY (`sleep_stage_id`)
    REFERENCES `health_project_db`.`sleep_stages` (`stage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`anomaly_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`anomaly_types` (
  `anomaly_id` INT NOT NULL AUTO_INCREMENT,
  `anomaly_type` VARCHAR(100) NULL,
  PRIMARY KEY (`anomaly_id`),
  UNIQUE INDEX `anomaly_id_UNIQUE` (`anomaly_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`anomaly_severity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`anomaly_severity` (
  `anomaly_severity_id` INT NOT NULL AUTO_INCREMENT,
  `anomaly_severity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`anomaly_severity_id`),
  UNIQUE INDEX `idanomaly severity_UNIQUE` (`anomaly_severity_id` ASC) VISIBLE,
  UNIQUE INDEX `anomaly severity_UNIQUE` (`anomaly_severity` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`readings_anomalies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`readings_anomalies` (
  `user_id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `anomaly_id` INT NOT NULL,
  `anomaly_severity_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `timestamp`, `anomaly_id`, `anomaly_severity_id`),
  INDEX `fk_readings_anomalies_anomaly_type1_idx` (`anomaly_id` ASC) VISIBLE,
  INDEX `fk_readings_anomalies_anomaly severity1_idx` (`anomaly_severity_id` ASC) VISIBLE,
  CONSTRAINT `fk_readings_anomalies_readings_heart1`
    FOREIGN KEY (`user_id` , `timestamp`)
    REFERENCES `health_project_db`.`readings` (`user_id` , `timestamp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_readings_anomalies_anomaly_type1`
    FOREIGN KEY (`anomaly_id`)
    REFERENCES `health_project_db`.`anomaly_types` (`anomaly_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_readings_anomalies_anomaly severity1`
    FOREIGN KEY (`anomaly_severity_id`)
    REFERENCES `health_project_db`.`anomaly_severity` (`anomaly_severity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`performance_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`performance_level` (
  `performance_level_id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`performance_level_id`),
  UNIQUE INDEX `performance_level_UNIQUE` (`level` ASC) VISIBLE,
  UNIQUE INDEX `idperformance_level_UNIQUE` (`performance_level_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`sleep_quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`sleep_quality` (
  `sleep_quality_id` INT NOT NULL AUTO_INCREMENT,
  `quality_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sleep_quality_id`),
  UNIQUE INDEX `sleep_quality_id_UNIQUE` (`sleep_quality_id` ASC) VISIBLE,
  UNIQUE INDEX `quality_level_UNIQUE` (`quality_level` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`fitness_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`fitness_level` (
  `fitness_level_id` INT NOT NULL AUTO_INCREMENT,
  `fitness_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fitness_level_id`),
  UNIQUE INDEX `idfitiness_level_UNIQUE` (`fitness_level_id` ASC) VISIBLE,
  UNIQUE INDEX `fitiness_level_UNIQUE` (`fitness_level` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`users_lifestyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`users_lifestyle` (
  `user_id` INT NOT NULL,
  `performance_level_id` INT NOT NULL,
  `sleep_quality_id` INT NOT NULL,
  `fitness_level_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `performance_level_id`, `sleep_quality_id`, `fitness_level_id`),
  INDEX `fk_users_lifestyle_performance_level1_idx` (`performance_level_id` ASC) VISIBLE,
  INDEX `fk_users_lifestyle_sleep_quality1_idx` (`sleep_quality_id` ASC) VISIBLE,
  INDEX `fk_users_lifestyle_fitiness_level1_idx` (`fitness_level_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_lifestyle_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_project_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_lifestyle_performance_level1`
    FOREIGN KEY (`performance_level_id`)
    REFERENCES `health_project_db`.`performance_level` (`performance_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_lifestyle_sleep_quality1`
    FOREIGN KEY (`sleep_quality_id`)
    REFERENCES `health_project_db`.`sleep_quality` (`sleep_quality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_lifestyle_fitiness_level1`
    FOREIGN KEY (`fitness_level_id`)
    REFERENCES `health_project_db`.`fitness_level` (`fitness_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `health_project_db`.`habits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`habits` (
  `habit_id` INT NOT NULL AUTO_INCREMENT,
  `habit_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`habit_id`),
  UNIQUE INDEX `lifestyle_id_UNIQUE` (`habit_id` ASC) VISIBLE,
  UNIQUE INDEX `lifestyles_type_UNIQUE` (`habit_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_project_db`.`users_habits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_project_db`.`users_habits` (
  `user_id` INT NOT NULL,
  `habit_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `habit_id`),
  INDEX `fk_user_habits_habits1_idx` (`habit_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_habits_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_project_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_habits_habits1`
    FOREIGN KEY (`habit_id`)
    REFERENCES `health_project_db`.`habits` (`habit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
